### ISSUE TITLE
Error: After filtering out keys not in the schema, your modifier is now empty

### ISSUE THREAD

**Issue by zzh1234567** [copleykj/socialize-feed#1]
After meteor add socialize:feed,  My Meteor Server can not run.

Error: After filtering out keys not in the schema, your modifier is now empty
    at doValidate (packages/aldeed:collection2/collection2.js:423:11)
    at Collection.Mongo.Collection.(anonymous function) (packages/aldeed:collection2/collection2.js:195:14)
    at Collection.Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user.js:325:19)
    at Object._updateUserRoles (packages/alanning_roles.js:755:22)
    at Object.addUsersToRoles (packages/alanning_roles.js:221:11)
    at Object.assignOwnerRoles (server/api/core/assignRoles.js:98:9)
    at Shops.find.forEach.shop (server/api/core/core.js:979:14)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1054:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:876:44)
    at _each (server/api/core/core.js:974:20)

**Comment by copleykj** [comment]
This is due to the use of the `socialize:user-model` attaching a schema to `Meteor.users`. You'll need to use `Meteor.users.attachSchema` to append a roles field to the current schema which defines the shape of that field on the document.
